spring:
  sql:
    init:
      mode: always
      # data-locations: classpath:static/data/data.sql
      encoding: utf-8
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

server:
  servlet:
    encoding:
      force-response: true